In [159]:
import numpy as np
import pandas as pd
import csv
try:  
  from faker import Faker
except:
  !pip install faker
  from faker import Faker
import random
import decimal
import time

In [160]:
fake = Faker()

In [161]:
print(random.random())

0.6100447112655343


In [162]:
max_alt = 10000/100000
vel = [220/100000*random.random(),220/100000*random.random(),0]
acc = [-1/100*random.random(),-1/100*random.random(),(-10+random.random())/100000]

src_lat, src_lon  = float(fake.latitude()), float(fake.longitude())
d_lat , d_lon = float(fake.latitude()), float(fake.longitude())
print(src_lat, src_lon,d_lat,d_lon)

src_alt = max_alt * (random.random()/2+0.5) * 1.5
# src_lat , src_lon = fake.latitude()+(np.random.normal(0,1,1)+0.5)*100 , fake.longitude()+(np.random.normal(0,1,1)+0.5)*100
# print (src_lat,src_lon)
# src_alt = random.random() * max_alt

-52.8517745 120.367266 -11.6080465 -106.473814


In [163]:
max_dist=1
d_lat = src_lat + ((np.random.normal(0,1,1)+0.5)*max_dist)
d_lon = src_lon + (np.random.normal(0,1,1)+0.5)*max_dist

d_lat, d_lon = d_lat[0],d_lon[0]
print(d_lat,d_lon)
src_lat = d_lat
src_lon = d_lon
print(src_lat,src_lon)

-53.48288744505226 120.63842218426304
-53.48288744505226 120.63842218426304


In [164]:
alt = src_alt
lats=[d_lat]
lons=[d_lon]
alts=[src_alt]
while(alts[-1]>0):
  acc[2] = (-10 + random.random())/100000
  lats.append(lats[-1]+vel[0])
  lons.append(lons[-1]+vel[1])
  alts.append(alts[-1]+vel[2])
  vel = np.add(vel,np.multiply(acc,[vel[0],vel[1],1]))
  # print(vel , np.multiply(acc,[vel[0],vel[1],1]))
  # print(vel,alt)
  alt = alt + vel[2]
  # acc = [-1/100*random.random()*vel[0],-1/100*random.random()*vel[1],-10/100000]
# print(alt)

In [165]:
print(np.array([lats,lons,alts]))
print(alts)

[[-5.34828874e+01 -5.34813814e+01 -5.34798900e+01 -5.34784131e+01
  -5.34769507e+01 -5.34755024e+01 -5.34740683e+01 -5.34726481e+01
  -5.34712418e+01 -5.34698492e+01 -5.34684701e+01 -5.34671045e+01
  -5.34657522e+01 -5.34644130e+01 -5.34630869e+01 -5.34617738e+01
  -5.34604734e+01 -5.34591856e+01 -5.34579104e+01 -5.34566477e+01
  -5.34553972e+01 -5.34541589e+01 -5.34529327e+01 -5.34517184e+01
  -5.34505160e+01 -5.34493252e+01 -5.34481461e+01 -5.34469785e+01
  -5.34458222e+01 -5.34446772e+01 -5.34435433e+01 -5.34424205e+01
  -5.34413086e+01 -5.34402076e+01 -5.34391172e+01 -5.34380375e+01
  -5.34369684e+01 -5.34359096e+01 -5.34348611e+01 -5.34338229e+01
  -5.34327947e+01 -5.34317766e+01 -5.34307684e+01 -5.34297701e+01
  -5.34287814e+01 -5.34278024e+01 -5.34268329e+01 -5.34258728e+01
  -5.34249222e+01 -5.34239807e+01 -5.34230485e+01 -5.34221253e+01
  -5.34212111e+01 -5.34203058e+01]
 [ 1.20638422e+02  1.20639498e+02  1.20640566e+02  1.20641626e+02
   1.20642679e+02  1.20643723e+02  1.2064

In [166]:
start = int(time.time()-(random.random()*10000))
print(start)
# print(orig_alt.shape)
t = start + np.linspace(1,len(alts),len(alts))
t = t.reshape(1,len(t))

1596441631


In [167]:
data = np.array([lats,lons,alts])
data = np.concatenate((t,data),axis=0)
print(data.shape)
data = np.transpose(data)
data = np.multiply(data,[1,1,1,100000])
print(data)

(4, 54)
[[ 1.59644163e+09 -5.34828874e+01  1.20638422e+02  1.28202980e+04]
 [ 1.59644163e+09 -5.34813814e+01  1.20639498e+02  1.28202980e+04]
 [ 1.59644163e+09 -5.34798900e+01  1.20640566e+02  1.28109051e+04]
 [ 1.59644164e+09 -5.34784131e+01  1.20641626e+02  1.27917817e+04]
 [ 1.59644164e+09 -5.34769507e+01  1.20642679e+02  1.27626605e+04]
 [ 1.59644164e+09 -5.34755024e+01  1.20643723e+02  1.27245020e+04]
 [ 1.59644164e+09 -5.34740683e+01  1.20644759e+02  1.26767023e+04]
 [ 1.59644164e+09 -5.34726481e+01  1.20645788e+02  1.26195971e+04]
 [ 1.59644164e+09 -5.34712418e+01  1.20646809e+02  1.25532961e+04]
 [ 1.59644164e+09 -5.34698492e+01  1.20647822e+02  1.24772973e+04]
 [ 1.59644164e+09 -5.34684701e+01  1.20648828e+02  1.23914932e+04]
 [ 1.59644164e+09 -5.34671045e+01  1.20649826e+02  1.22963252e+04]
 [ 1.59644164e+09 -5.34657522e+01  1.20650816e+02  1.21919165e+04]
 [ 1.59644164e+09 -5.34644130e+01  1.20651799e+02  1.20781686e+04]
 [ 1.59644165e+09 -5.34630869e+01  1.20652775e+02  1.1

In [168]:
d = pd.DataFrame(data=data,columns = ["t","lat","lon","alt"])
d.to_csv('data/traj'+str(count)+'.csv', sep=",", index=False)
count = count +1
print(count)

31


In [169]:
  # count = 21

In [170]:
# from google.colab import drive 
# drive.mount('/mntDrive') 


In [171]:
# ! cp  "/content/data/traj30.csv" "/mntDrive/My Drive/synthesis/data/"